# Generated by Django 5.2 on 2025-04-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
