# Generated by Django 5.2 on 2025-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_project_url_project_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
