# Generated by Django 5.2 on 2025-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_project_github_link_alter_project_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default='📁', max_length=10),
        ),
    ]
