# Generated by Django 5.2 on 2025-10-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_alter_post_options_alter_project_options_and_more'),
    ]

    operations = [
    ]
