# Generated by Django 5.2 on 2025-10-20 21:23

from django.db import migrations
from django.utils.text import slugify

def ensure_unique_slug(qs, base_slug, *, exclude_pk=None, extra_filter=None):
    """
    Ensure slug is unique within qs (optionally with extra_filter for composite scope).
    """
    slug = base_slug or "item"
    if not slug:
        slug = "item"
    cand = slug
    i = 2
    flt = {"slug": cand}
    if exclude_pk:
        flt["pk__ne"] = exclude_pk  # placeholder; we’ll handle manually below
    while True:
        query = qs.filter(slug=cand)
        if exclude_pk:
            query = query.exclude(pk=exclude_pk)
        if extra_filter:
            query = query.filter(**extra_filter)
        if not query.exists():
            return cand
        cand = f"{slug}-{i}"
        i += 1

def forwards(apps, schema_editor):
    Project = apps.get_model("blog", "Project")
    Post = apps.get_model("blog", "Post")

    # ---- Projects ----
    for p in Project.objects.all().order_by("id"):
        base_text = getattr(p, "name", None) or getattr(p, "title", None) or f"project-{p.pk}"
        desired = slugify((p.slug or "").strip() or base_text)
        unique = ensure_unique_slug(Project.objects.all(), desired, exclude_pk=p.pk)
        if p.slug != unique:
            p.slug = unique
            p.save(update_fields=["slug"])

    # ---- Posts ----
    # Decide your scope: (a) unique across all posts OR (b) unique per project
    # (a) global uniqueness:
    per_project = False  # set True if you want uniqueness per project

    for post in Post.objects.select_related("project").all().order_by("id"):
        base_text = getattr(post, "title", None) or getattr(post, "name", None) or f"post-{post.pk}"
        desired = slugify((post.slug or "").strip() or base_text)

        if per_project and getattr(post, "project_id", None):
            unique = ensure_unique_slug(
                Post.objects.all(), desired, exclude_pk=post.pk, extra_filter={"project_id": post.project_id}
            )
        else:
            unique = ensure_unique_slug(Post.objects.all(), desired, exclude_pk=post.pk)

        if post.slug != unique:
            post.slug = unique
            post.save(update_fields=["slug"])

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_populate_project_slugs'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=noop),
    ]