# Generated by Django 5.2 on 2025-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, default='📁', max_length=10),
        ),
    ]
