# Generated by Django 5.2 on 2025-11-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_project_is_published_alter_post_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='added_at',
        ),
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.project'),
        ),
    ]
