# Generated by Django 5.2 on 2026-09-05 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_project_added_at_project_published_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('pending', 'Hold as pending'), ('reject', 'Reject'), ('spam', 'Mark as spam')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Automation', 'Automation'), ('Development', 'Development'), ('Productivity', 'Productivity'), ('Life', 'Life'), ('Travel', 'Travel')], default='Development', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Automation', 'Automation'), ('AI', 'AI'), ('Web Apps', 'Web Apps'), ('Infrastructure', 'Infrastructure'), ('Hardware', 'Hardware'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='failure_handling',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='integrations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons',
            field=models.TextField(blank=True, help_text='One lesson per line.'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_screenshots/%Y/%m/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='blog.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='pending', max_length=16)),
                ('moderation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.project')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('project__isnull', True)), models.Q(('post__isnull', True), ('project__isnull', False)), _connector='OR'), name='comment_exactly_one_target')],
            },
        ),
    ]
