from django.utils import timezone
from django.core.exceptions import ValidationError
import pytest

from blog.tests.factories import PostFactory, ProjectFactory, TagFactory
from blog.models import Post

pytestmark = pytest.mark.django_db


def test_slug_autogenerated_when_missing() -> None:
    p = PostFactory.build(slug="")
    p.save()
    assert p.slug  # not empty
    assert len(p.slug) <= 200


def test_slug_not_regenerated_on_update():
    p = PostFactory.create(slug="")
    old_slug = p.slug
    p.title = "New title"
    p.save()
    assert p.slug == old_slug


def test_unique_slug_when_titles_duplicate():
    p1 = PostFactory.create(title="Same Title", slug="")
    p2 = PostFactory.create(title="Same Title", slug="")
    assert p1.slug != p2.slug


def test_post_related_to_project_and_tags() -> None:
    project = ProjectFactory.create()
    tags_names = ['python', 'django', 'git']
    tags = [
        TagFactory.create(name=tag_name) for tag_name in tags_names]

    post = PostFactory.create(project=project)
    for tag in tags:
        post.tag.add(tag)

    assert post.project == project
    assert post.tag.count() == len(tags_names)
    assert (
        list(post.tag.values_list('slug', flat=True)) == tags_names
    )


def test_publish_sets_published_at_when_missing():
    p = PostFactory.create(is_published=True, published_at=None)
    assert p.is_published is True
    assert p.published_at is not None


def test_can_set_published_at_when_published():
    now = timezone.now()
    p = PostFactory.create(is_published=True, published_at=now)
    assert p.published_at == now


def test_str_includes_id_and_title():
    p = PostFactory.create(title="Hello")
    s = str(p)
    assert f"(Post # {p.pk})" in s
    assert "Hello" in s


def test_created_at_and_updated_at_set():
    p = PostFactory.create()
    assert p.created_at is not None
    assert p.updated_at is not None


def test_updated_at_changes_on_save():
    p = PostFactory.create()
    first_updated = p.updated_at
    p.title = "Changed"
    p.save()
    assert p.updated_at > first_updated


def test_title_max_length_enforced():
    p = PostFactory.build(title="x" * 201)
    with pytest.raises(ValidationError):
        p.full_clean()


def test_slug_max_length_enforced_even_when_set_manually():
    p = PostFactory.build(slug="x" * 201)
    with pytest.raises(ValidationError):
        p.full_clean()


def test_default_ordering_is_newest_first():
    older = PostFactory.create()
    newer = PostFactory.create()
    qs = list(Post.objects.all())
    assert qs[0] == newer
    assert qs[1] == older


def test_project_set_null_on_delete(project=None):
    project = project or ProjectFactory.create()
    post = PostFactory.create(project=project)
    project.delete()
    post.refresh_from_db()
    assert post.project is None


def test_can_add_and_remove_tags():
    p = PostFactory.create()
    t1, t2 = TagFactory.create(), TagFactory.create()
    p.tag.add(t1, t2)
    assert set(p.tag.all()) == {t1, t2}
    p.tag.remove(t1)
    assert list(p.tag.all()) == [t2]